# Generated by Django 2.2.4 on 2021-02-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semirestful_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(),
        ),
    ]
